### ISSUE TITLE
Implement new naming

### ISSUE THREAD

**Issue by hdrury1** [hivereview/thehive#196]
hivereview should be registered on the following platforms:

- [x] Email
- [x] GitHub
  - [x] Rename 'master' branch to 'main'
- [x] Twitter (claim an impersonation - need to register domain and email first)
- [ ] ~Instagram~
- [ ] ~Slack channels~
- [ ] ~Codebase~
- [ ] AWS
  - [ ] Cloudwatch dashboard name and link in README
- [ ] URLS
  - [ ] DNS
    - [ ] Delegation from @BlueReZZ DNS provider
    - [x] `external-dns`
    - [x] Github workflows of `thehive`
  - [x] Twitter callback
- [x] User-facing page titles
- [x] About page
- [ ] Docker (use GitHub packages instead)
- [ ] Feedback form
~- NPM~

**Comment by BlueReZZ** [comment]
Created the twitter account today #222 and attempted an impersonation request for @thehive

**Comment by thewilkybarkid** [comment]
On GitHub or Twitter?

**Comment by BlueReZZ** [comment]
> On GitHub or Twitter?

Twitter, then if that doesn't work, try and claim `@hivereview` to match @hivereview 

It wasn't until I saw the link turn to GitHub that I realised there was one we could claim.

**Comment by BlueReZZ** [comment]
There are 4 cards on the Miro Kanban board that cover the 4 remaining tasks in here

**Comment by giorgiosironi** [comment]
According to https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/migrate-dns-domain-inactive.html, change the `NS` records on the other DNS provider to:
```
ns-369.awsdns-46.com.
ns-1354.awsdns-41.org.
ns-1700.awsdns-20.co.uk.
ns-532.awsdns-02.net.
```
which come from https://console.aws.amazon.com/route53/v2/hostedzones#ListRecordSets/Z0299021AEV76N8DAORB

**Comment by giorgiosironi** [comment]
NS records have propagated according to https://checkdns.one/#/NS/hive.review and `staging.hive.review` is working correctly. So deploying production to create the `hive.review` A record.
