### ISSUE TITLE
Ingest reviews and endorsements from Peer Community In

### ISSUE THREAD

**Issue by BlueReZZ** [hivereview/thehive#204]
Peer Community In have 15 communities each with their own RSS feed of content.

The content is available by either a bioRxiv-specific RSS feed: https://evolbiol.peercommunityin.org/public/rss4bioRxiv or a more comprehensive RSS feed: https://evolbiol.peercommunityin.org/public/rss

They have the ability to create a new RSS feed for us based on one of these. We have access to their development team to add what we need in order to show all of the content we would like.

We know that the content in the RSS feed is used to create a listings page: https://evolbiol.peercommunityin.org/public/all_recommended_articles

...but it is not enough to create a full version of the review and recommendation, like this:
https://evolbiol.peercommunityin.org/public/rec?id=221&reviews=True

Another interesting aspect is the importance in their community of the Author Response which is usually a PDF link.

Our task is to define the complete RSS feed that we would like, including any missing data, semantics or nesting, that would allow us to ingest all of their content from a feed.

- [x] create a script to turn a PCI feed into json
- [x] create a PCI community & give it an ID
- [x] obtain text for PCI community page & lob it in
- [x] ~find out how to get historical PCI content (beyond what the RSS supplies)~ _the RSS feed is a complete list of all content_
- ~First pass: implement this by adding a ReviewId that is just the [URL](https://evolbiol.peercommunityin.org/public/rec?id=221&reviews=True)~
- ~Second pass: show the `added` Date as a fallback since we cannot fetch one from this URL~
- [x] Demo reviews only internally, and ask whether to add endorsements

## Communities to add
- [x] https://evolbiol.peercommunityin.org/public/rss4bioRxiv
- [x] https://ecology.peercommunityin.org/public/rss4bioRxiv
- [x] https://animsci.peercommunityin.org/public/rss4bioRxiv
- [x] https://zool.peercommunityin.org/public/rss4bioRxiv
- [x] https://archaeo.peercommunityin.org/public/rss4bioRxiv
- [x] https://paleo.peercommunityin.org/public/rss4bioRxiv

**Comment by giorgiosironi** [comment]
First pass: implement this by adding a `ReviewId` that is just the [URL](https://evolbiol.peercommunityin.org/public/rec?id=221&reviews=True):
![Screenshot_2020-07-27 The Hive](https://user-images.githubusercontent.com/160299/88555246-72fd7c00-d01f-11ea-8c90-2297ade7da13.png)

Second pass: show the `added` Date as a fallback since we cannot fetch one from this URL.

**Comment by giorgiosironi** [comment]
There's a list of potential "competitors" in the indexed-by section of https://evolbiol.peercommunityin.org/about/about

**Comment by BlueReZZ** [comment]
Updated the todo list here to reflect that the RSS feed is a complete list of all content so no need to investigate the historical list of content for PCI.

**Comment by thewilkybarkid** [comment]
We should close this now?

**Comment by BlueReZZ** [comment]
Yes, last task was updating the actual text for PCI communities which was done :heavy_check_mark:
