### ISSUE TITLE
Automate ingestion of new content for existing communities (scripts to be run manually)

### ISSUE THREAD

**Issue by hdrury1** [hivereview/thehive#217]
What do we have?
- Communities: where do we fetch their content from?
- Script per community

What's missing?
What development work is left to do?

- [x] Fetch eLife reviews from Hypothes.is
- [x] Fetch Review Commons reviews from Hypothes.is
- [x] Fetch PeerJ reviews from Crossref

**Comment by thewilkybarkid** [comment]
Working out what we have and what we need in https://docs.google.com/spreadsheets/d/1j0MDb0XBS_WyJd-r2-noG9J5oKOw0Yj0Ku_ebL2QMcQ/edit#gid=0

**Comment by kevinrutherford** [comment]
See [here](https://unix.stackexchange.com/questions/345076/sorting-csv-file-by-first-column-ignoring-header) for how to sort a CSV file with a header row.

**Comment by giorgiosironi** [comment]
eLife and Review Commons reviews now are covered with scripts, direction is needed to prioritize between:
- PeerJ reviews
- PCI (how many communities?) reviews or endorsements

**Comment by giorgiosironi** [comment]
For PeerJ reviews:
1. use the Biorxiv API we use for endorsments to find the PeerJ article DOI related to every Biorxiv article DOI
2. Load this list of reviews from PeerJ related to that PeerJ article DOI: https://api.crossref.org/prefixes/10.7287/works?filter=type:peer-review,relation.object:10.7717/peerj.9572

The review DOI is there.

`created` or `indexed` dates are about when the record was created on Crossref, so they only approximate the original review.

**Comment by giorgiosironi** [comment]
PCI is in #218 or #204 so closing this that has completed the other communities.
