### ISSUE TITLE
Replace the homepage feed with onboarding text for new users

### ISSUE THREAD

**Issue by giorgiosironi** [hivereview/thehive#231]
DoD

- [x] business logic i.e. 4 cases validated
- [x] meets design principles
- [x] happy with level of unit tests
- [x] UI is keyboard navigable

To be discussed / To Do

- [x] UI is screenreader compatible
- [x] ~clean up, reduce duplication in `home-page/project-is-following.test.ts`~
      experimented, will dive into this when we write next projection. Current idea: factory function in type code
- [x] ~feature test~
- [x] we can measure success (TBD qualitatively through interviews)
- [x] user journey can be completed

**Comment by hdrury1** [comment]
https://docs.google.com/document/d/1xjLhxD1vRgWZVCVj8T2kZj4bAsE_WXqnDTWINdc7284/edit
