### ISSUE TITLE
Provide context when logging in with Twitter

### ISSUE THREAD

**Issue by hdrury1** [hivereview/thehive#232]
Explain to the user how we will use their account name.

Opportunity: Users clicking follow (especially when on a deep link) currently get dropped on Twitter sign in without context leading to confusion.

It tidies up us adding authentication.

## Current (and future routes)

- `Log in` in welcome text
- `Follow` button
- `Sign In` in nav area

### Journeys

- [x] Log in entry points have context > auth page has more context
- [x] Follow button > auth page has context

## Solution

improve text on:
- [x] home page (login with twitter)
- [x] twitter auth page (use text written for interstitial)

### Out of scope

- modal
- tooltips etc. for follow button
- adding context re: auth around folllow button
- cancel button redirect back to where you came from
- avoiding/dealing with twitter errors

## Success

- [x] Interview people who complained about this

## Content

Text for the page can be found here:

https://docs.google.com/document/d/1xjLhxD1vRgWZVCVj8T2kZj4bAsE_WXqnDTWINdc7284/edit

We should use the recognisable 'Sign in with Twitter' button to establish trust.

**Comment by thewilkybarkid** [comment]
We've used the second paragraph as there's a 200 character limit unfortunately. It probably needs tweaking given the context it appears in:

![Screenshot 2020-09-15 at 15 14 19](https://user-images.githubusercontent.com/1784740/93221862-281dfc00-f766-11ea-8bd0-c33c87d3e63e.png)

**Comment by giorgiosironi** [comment]
Unclear whether the Twitter text is picked up by screen readers.
