### ISSUE TITLE
node-forge vulnerability

### ISSUE THREAD

**Issue by thewilkybarkid** [hivereview/thehive#238]

**Comment by erkannt** [comment]
util.setPath doesn't appear to be used by rdf-canonize, which is the dependant

**Comment by thewilkybarkid** [comment]
(Only used in a browser, not Node.js)

**Comment by thewilkybarkid** [comment]
Alert seemed to reopen so closing as 'Vulnerable code is not actually used' again.

**Comment by giorgiosironi** [comment]
https://github.com/digitalbazaar/rdf-canonize/pull/29 was closed without merging because `node-forge` got up to date on their master branch.
