### ISSUE TITLE
Spike: can we ingest content from PCI website and how reliable is this method?

### ISSUE THREAD

**Issue by erkannt** [hivereview/thehive#240]
Currently we don't ingest the review text, only a link to it. Subsequent ticket want to add full review text to article page.

RSS link adapted by PCI after request from Paul: https://zool.peercommunityin.org/public/rss4elife

RSS feed contains doi to article and doi to pci review page: https://zool.peercommunityin.org/public/rec?id=2&reviews=True

Above example page contains:

- recommendation (summary text) based on reviews
- reviews as text
- supplementary content of reviews as pdf
- authors response

Interested in all of the above, to represent them as reviews on the Hive.

## current state

- store DOI, try to find content via this

## Questions

- [x] Is anything for these review DOI stored on crossref that we can retrieve? Not for full text, only for metadata and only about the recommendation rather than the individual reviews (see comments).
- [x] what identifier do we store in the hive? The recommendation is DOIed but the individual reviews (and similar) are not and we would have to invent an identifier for them.
- [x] Do we request them to store content in e.g. crossref, zenodo? They already integrate, but without text, only metadata.
- [x] Do we ask them to put in another feed? API? Possible, incurring development time from their side.
- [x] Do we scrape from webpage (urgh)? Possible but very brittle.

## Out of scope

- alt metrics such as blogged by / tweeted by

**Comment by giorgiosironi** [comment]
```
curl -v -L -H "Accept: application/vnd.crossref.unixref+xml" "https://doi.org/10.24072/pci.animsci.100001" | less
```
has some content.

**Comment by giorgiosironi** [comment]
```
curl -v -L -H "Accept: application/vnd.crossref.unixref+xml" "https://doi.org/10.24072/pci.evolbiol.100107" | less
```
has a link to CLOCKSS worth investigating:
```
          <archive_locations>
            <archive name="CLOCKSS" />
          </archive_locations>
```

**Comment by thewilkybarkid** [comment]
The information inside the revision rounds (decision letter, individual reviews and author response) has no DOI and little meaningful HTML or metadata (eg RDFa). The only possibility, as it stands, is to understand there HTML structure and parse it (eg to understand what `<h4>Reviewed by <a href="/public/viewUserCard?userId=1054">Luca Ferretti</a>, 2020-07-22 11:49</h4>` means).

**Comment by thewilkybarkid** [comment]
The HTML text of the recommendation seems to be located at `.pci-article-div:first > .pci-recommendation-div:first > .pci-bigtext`. This also includes the references as HTML.

**Comment by thewilkybarkid** [comment]
https://zool.peercommunityin.org/public/rec?id=4&reviews=True has multiple rounds of review, visually nested rather than HTML nested.

**Comment by giorgiosironi** [comment]
Noting we could associate the DOI of the recommendation to the whole content of the PCI page, treating recommendation and reviews as a monolithic entity.
