### ISSUE TITLE
Timeout on update script silently removes all reviews of a community

### ISSUE THREAD

**Issue by giorgiosironi** [hivereview/thehive#251]
```
docker-compose --file .docker/docker-compose.yml --file .docker/docker-compose.dev.yml run -T app npx ts-node scripts/find-reviews-from-crossref-via-biorxiv 10.7717 10.7287 \
| tee ./data/reviews/53ed5364-a016-11ea-bb37-0242ac130002.csv
Date,Article DOI,Review ID
Error: connect ETIMEDOUT 143.48.220.223:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
```
Exit code of `$ make update-event-data` was 0.

**Comment by thewilkybarkid** [comment]
Discovered that the exit code is from `tee`, not the script.

**Comment by thewilkybarkid** [comment]
Rather than looking at improvements of writing files only on success or retrying requests, we've moved the update script task to the top of the retro list so it can be hopefully mitigated with a human process of checking the diff in a pair/mob before committing.
