### ISSUE TITLE
How can we handle occasions when Crossref is down?

### ISSUE THREAD

**Issue by hdrury1** [hivereview/thehive#271]
- [x] decorate `fetchCrossrefArticle`
- [x] ~abstract `FetchArticle` type for decorator?~
- [x] decorator should be in its own module
- [x] unit tests for decorator
  - [x] implement whole test list
  - [x] ~consider `jest.*` utilities for mocks~
  - [x] revise language of tests
- [x] any logging?
- [x] look at production logs to see effect
- [x] check if there is a way to check memory usage
- [x] check memory usage after fresh deploy to understand cache size

**Comment by erkannt** [comment]
State of prod after 19h:

```
/app # ps -eo pid,comm,vsz,rss
PID   COMMAND          VSZ  RSS
    1 node             283m  43m
   17 node             332m 101m
   28 sh               1652  932
   49 ps               1572    4

```

**Comment by erkannt** [comment]
Fresh pod:

```
/app # ps -eo pid,comm,vsz,rss
PID   COMMAND          VSZ  RSS
    1 node             282m  43m
   17 node             316m  77m
   28 sh               1652    4
   33 ps               1572    4

```
