### ISSUE TITLE
Add article version to article page feed

### ISSUE THREAD

**Issue by hdrury1** [hivereview/thehive#279]
- [x] add current date as `version 1` in the feed
  - [x] define `ArticleVersionFeedItem` type
  - [x] extract `renderVersionFeedItem`
  - [x] rename other subcomponent to `renderReviewFeedItem`
  - [x] expand `GetReviews` port to return multiple view models
    - [x] move hardcoded view model in here
    - [x] `Review` -> `ReviewFeedItem`
    - [x] `GetReviews` -> `...`
    - [x] ports of `GetReviews`
    - [x] expand `GetFeedEvents` to return two different types
    - [x] rename `GetReviews`
    - [x] push hardcoding out of `GetReviews` and into the `index`
  - [x] implement version 1 in the `index` using `ports.fetchArticle` and building the bioRxiv URL by hand
    - [x] extract into its own `hardcoded` module
    - [x] remove feature flag to roll out
    - [x] is `unsafelyUnwrap` the best thing to do?
  - [x] check direction of exports between `render-feed` and its subcomponents
  - [x] should `render-feed` have a test scenario for version items?
  - [x] unit tests have outdated file and `describe` names
  - [x] `render-feed` uses `Object.prototype.hasOwnProperty.call(feedItem, 'postedAt')` to write a type guard, dirty?
  - [x] similar type guard not using a `type` field in `get-feed-events-content`
  - [x] we sometimes use `version` rather than `articleVersion` in names and this could be confusing or inconsistent (e.g. review may have versions too?)
  - [x] unit test coverage for `article-page`
- [x] remove posted date from article page header
- [x] add all the other versions
  - [x] transform/replace the hardcoded adapter to allow multiple versions
  - [x] rename the `hardcoded` module to refer to ~sorting/Composite~ `biorxiv` rather than hardcoding
  - [x] types of the ports of the `hardcoded` module
  - [x] version events should be inserted in the right place, keeping the descending order
  - [x] unify `postedAt` and `occurredAt`
  - [x] call the biorxiv API to get the versions and the dates
  - [x] keep building the URLs manually with the `v{version}` suffix
  - [x] consider splitting the `hardcoded` module if it has too many responsibilities
  - [x] validation on `BiorxivResponse` and `parseInt` rather than blind casting
  - [x] test with an article that has many versions
  - ~test with an article whose title changes across versions~
  - [x] move getJson and translation out of the adapter
- [x] consider renaming anything that refers to `articleVersionDoi`s
- [x] handle errors arising from biorxiv
  - [x] ~biorxiv returns `not found`~ page would fail
  - [x] on error: feed item at bottom, biorxiv avatar, msg: posted to biorxiv, unable to fetch further information, try refreshing
  - [x] test the new feed item type
- [x] look at logging request to bioRxiv
- [x] define a test card

**Comment by giorgiosironi** [comment]
```
curl -v -L -H "Accept: application/vnd.crossref.unixref+xml" "https://doi.org/10.1101/646810" | less
```
doesn't give us version information, but
```
https://api.biorxiv.org/details/biorxiv/10.1101/646810
```
does.

**Comment by giorgiosironi** [comment]
Good test case with 4 versions:
http://localhost:8080/articles/10.1101/849851
