### ISSUE TITLE
Set up Google Analytics with basic measurements

### ISSUE THREAD

**Issue by giorgiosironi** [hivereview/thehive#286]
- [x] exclude internal traffic somehow (e.g. developers using `hive.review`)
  -  we all use browsers that block tracking, so we appear to not be generating traffic in analytics
- [x] inform others to use blockers or not to consent to cookies
- [x] switch from classic to Google Tag Manager
  - [x] add `script` to head
  - [x] add `noscript` to body
  - [x] ensure consent is given
    - [x] `<head>`
    - ~`<noscript>`~
  - [x] modify helm chart and values to enable only on prod
  - [x] pass in GTM id from Helm chart
  - [x] set up Google Analytics within GTM
- [x] remove Google Analytics standalone setup
  - [x] from code
  - [x] from Docker Compose
  - [x] from Helm
- [x] track external links
- [x] define/track a _fictional_ macro conversion goal e.g. login
- [x] define how we use `utm_` parameters when giving out links e.g. to tweet
- [x] add team as users to tag manager
- [x] add team as users to analytics
- [x] should we use `--set-string` for Helm values that end up in environment variables?

**Comment by giorgiosironi** [comment]
For reference: https://samuelschmitt.com/google-tag-manager-analytics-tutorial/ga-gtm-setup/#Install_Google_Analytics_with_Google_Tag_Manager

**Comment by erkannt** [comment]
## Example UTM links

Trying to develop a common understanding / usage.

Generated using: https://ga-dev-tools.appspot.com/campaign-url-builder/

- http://hive.review/?utm_source=twitter&utm_medium=social&utm_campaign=elife_preprint_review
- http://hive.review/?utm_source=direct_link&utm_medium=presentation&utm_campaign=2020_10_board_meeting
- http://hive.review/?utm_source=twitter&utm_medium=social&utm_campaign=article_page_sharing_button
- http://hive.review/?utm_source=direct_link&utm_medium=affiliate&utm_campaign=pci_advert
- http://hive.review/?utm_source=direct_link&utm_medium=affiliate&utm_campaign=pci_content_page

**Comment by giorgiosironi** [comment]
Twitter doesn't add UTM parameters while shortening URLs.

Take for example https://twitter.com/hivereview_/status/1306252195780849665 and navigate to it:

```
$ curl -v "https://t.co/oV7dzPFHiM?amp=1" -o /dev/null
...
> GET /oV7dzPFHiM?amp=1 HTTP/2
> Host: t.co
> User-Agent: curl/7.58.0
> Accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
< HTTP/2 301
...
< location: https://hive.review/articles/10.1101/2020.06.03.20119925
```

**Comment by giorgiosironi** [comment]
Set up the (fictional) conversion goal as loading an external link with the text `Read the full article`. Report is here:
https://analytics.google.com/analytics/web/?authuser=1#/report/conversions-goals-overview/a167311475w233457116p219087825/_u.date00=20201004&_u.date01=20201010&overview_goaloption_ALL-graphOptions.primaryConcept=analytics.goal1Completions&_.goalOption=1&overview_goaloption_1-dimensionSummary.selectedGroup=goals&overview_goaloption_1-dimensionSummary.selectedDimension=analytics.goalRequestUri
