### ISSUE TITLE
Add a privacy policy, and terms and conditions

### ISSUE THREAD

**Issue by BlueReZZ** [hivereview/thehive#290]
- [x] Create a page to hold terms and conditions at `/terms` 
- [x] Create a page to hold privacy notice at `/privacy`
- [x] Add content that explains the specific privacy use cases of The Hive [as written here](https://docs.google.com/document/d/1lyl3SyUIz-DgkQivnvtCLDoePV1gnbyFJXp6iOBvoRM/edit)
- [x] Add t[he text in the comment below](https://github.com/hivereview/thehive/issues/290#issuecomment-709948956) to the terms pages under the heading "Terms and conditions" 
- [x] Add a physical address and copyright notice to a footer
- [x] Style footer
  - [x] remove unnecessary `<section>` in home-page
  - [x] move `margin-bottom` from `section` to more specific selectors
  - [x] add `margin-bottom` to various places that come immediately before the footer e.g. `main`
  - [x] remove `margin-top` from `footer`
  - [x] remove `margin-bottom` from some last list items
  - [x] divide footer into 3 areas
- [x] remove semantic ui grids
  - [x] editorial community page
  - [x] about page
  - [x] user profile page
- [x] remove semantic ui from `summary-feed-list` in editorial-community-page
- [x] ~move `search-form` into its own sass partial~
- [x] Add in full business name for eLife
- [x] refactor out resulting sass duplication
  - [x] extract `home-page` SASS into its own partial
     - [x] grid
     - [x] everything else
  - [x] give all page headers the same following vertical whitespace
  - [x] `find-article` and `search-form`
    - [x] rename to the same thing
    - [x] extract SASS to its own partial
    - [x] extract `button` to its own partial
    - [x] ~remove CSS custom properties substituting with `settings`~
    - [x] remove coupling between `search` and `button` partials (about the search button)
- [x] Add new content for the terms page [from this comment](https://github.com/hivereview/thehive/issues/290#issuecomment-715388707)

**Comment by BlueReZZ** [comment]
Current draft of my proposal for the Privacy Notice page is here:
https://docs.google.com/document/d/1lyl3SyUIz-DgkQivnvtCLDoePV1gnbyFJXp6iOBvoRM/edit

I'm awaiting feedback from Paul Kelly on whether this, and our other planned changes are satisfactory.

**Comment by BlueReZZ** [comment]
Here's the text for the Terms and conditions page under a heading of "Terms and conditions"
> This website is operated by eLife Sciences Publications, Ltd under their terms and conditions as set out at https://elifesciences.org/terms

**Comment by BlueReZZ** [comment]
I've updated the description to include an additional page for the "Terms and conditions" along with links to content to add to the privacy and terms pages respectively

**Comment by thewilkybarkid** [comment]
Related reading: https://www.smashingmagazine.com/2020/10/website-policy-disclosure-pages/

**Comment by davidcmoulton** [comment]
@BlueReZZ Any text for the copyright notice / a license statement? We're using content from multiple sources from multiple authors that could in theory have multiple licensing terms.

**Comment by BlueReZZ** [comment]
Same as for eLife as it's a similar situation there:
> © 2020 eLife Sciences Publications Ltd. Subject to a Creative Commons Attribution license, except where otherwise noted.

**Comment by giorgiosironi** [comment]
The two links now appear on the Twitter OAuth form due to https://github.com/hivereview/thehive/issues/7#issuecomment-713596700:
![Screenshot_2020-10-21 Twitter Authorise an application](https://user-images.githubusercontent.com/160299/96737643-cfb9ca00-13b5-11eb-958c-97c86dff5718.png)

**Comment by BlueReZZ** [comment]
> The two links now appear on the Twitter OAuth form due to [#7 (comment)](https://github.com/hivereview/thehive/issues/7#issuecomment-713596700):

Excellent. This will go some way to countenance feedback we've had that expressed concern over our need to see protected Tweets, and mute/block lists. Unfortunately there doesn't appear to be a way to apply more granular permissions to our app in Twitter so perhaps we could adjust the text on the right to encourage people to read the privacy policy or explicitly call out the fact we don't read Tweets or mute/block lists. One for discussion perhaps /cc @hdrury1

**Comment by BlueReZZ** [comment]
Response from Paul Kelly regarding the footer:
> As for the company information in the footer, I think we ought to add the extra paragraph we use on the main site:
>
>"eLife Sciences Publications, Ltd is a limited liability non-profit non-stock corporation incorporated in the State of Delaware, USA, with company number 5030732, and is registered in the UK with company number FC030576 and branch number BR015634 at the address:"

I've added a task to the list to include this text in the footer - probably needs one to cover restyling it too since it's quite a lot of extra text.

**Comment by BlueReZZ** [comment]
New content for the Terms page, similar to Privacy now in that it has some Hive-only exceptions below the link:

> This website is operated by eLife Sciences Publications, Ltd under their terms and conditions as set out at elifesciences.org/terms unless otherwise stated through amendments below.
> 
> Exceptions to Ownership
> Unless otherwise indicated the Editorial Community names, logos and trademarks are owned by their respective owners and not by eLife or its licensors. The article content is created by the authors stated on the article page and is not owned by eLife or its licensors, and is subject to the licence terms shown against it. Evaluation content is created by the Editorial Community named alongside the evaluation content and is not owned by eLife or its licensors, and is subject to the licence terms shown on the Editorial Community's page.
