### ISSUE TITLE
Persist DB using RDS

### ISSUE THREAD

**Issue by erkannt** [hivereview/thehive#293]
## Prep
- [x] make RDS available (see [one possible approach](https://github.com/libero/infrastructure/commit/cda1862cbd7db98f376e3a555f3928f33897b84a))
  - [x] verify / add RDS module to terraform in libero infrastructure
  - [x] set up a staging RDS
  - [x] ensure the cluster has network access to the RDS

- [x] get password / host
- [x] enable local access to the RDS
- [x] enable local access to the database that lives inside the cluster
- [x] understand what needs to change in the Helm chart for the migration
- [x] get secrets into hive.review repo

## Migration
- [x] dump the data from the postgres pod
- [x] import the data into RDS
- [x] change Helm chart values to point at RDS
- [x] do the same for prod
- [x] remove Postgres chart
- [x] remove GitHub secret
- [x] remove `make list-users` as it is broken
- [x] ensure transaction log stops growing 

## Post Migration

- ~adjust DB storage size?~
- ~lock down RDS security group to only allow traffic from cluster~
- ~rotate db credentials?~
- ~`make sql` target~

**Comment by davidcmoulton** [comment]
To dump from postgres:
```sh
pg_dump -d [database-name] -U [user-name] -W -O > dump.sql
```

To read the dump into the RDS:
```sh
cat dump.sql | psql --host=[host-name] --dbname=[database-name] --username=[user-name] --password
```

**Comment by giorgiosironi** [comment]
The transaction log disk space [seems to have stabilized](https://console.aws.amazon.com/rds/home?region=us-east-1#database:id=hive-staging-postgres;is-cluster=false;tab=monitoring):
![Screenshot_2020-10-20 RDS · AWS Console](https://user-images.githubusercontent.com/160299/96594248-50a79180-12e2-11eb-8b2b-ed24653d77cf.png)
![Screenshot_2020-10-20 RDS · AWS Console(1)](https://user-images.githubusercontent.com/160299/96594251-51402800-12e2-11eb-8851-cbdc82bf5aac.png)
