### ISSUE TITLE
Set up RDS backups

### ISSUE THREAD

**Issue by erkannt** [hivereview/thehive#296]
- [x] add backups to prod RDS

## Previously decided to be out of scope

- [x] ~adjust DB storage size?~
- [x] ~lock down RDS security group to only allow traffic from cluster~
- [x] ~rotate db credentials?~
- [x] ~`make sql` target~

**Comment by thewilkybarkid** [comment]
Enabled 10-day backups to both prod and staging; turned on `apply_immediately` as we don't need to wait for maintenance windows (yet).
