### ISSUE TITLE
Add a Twitter card

### ISSUE THREAD

**Issue by hdrury1** [hivereview/thehive#298]
To help drive traffic to the site, eLife have asked that we add a Twitter card to the application, which will be pulled into social tweets containing links to article pages. This will help set user expectations and build trust before clicking links.

See https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards and https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

- [x] `twitter:card`
- [x] `twitter:site`: Twitter username (including the `@`)
- ~`og:type` is the type of content (e.g. `article`, `profile`; default is `website`)~
- [x] `og:title` is the title of the article (max 70 characters)
- [x] `og:description` has a 200 character limit
- [x] `og:image` is the asset provided below
- [x] refactor
  - [x] look at TODO comments
  - [x] some adapters could be extracted from `article-page` `index`
  - [x] `page-handler` has conditionals, can it be simplified by making more pages return `Result<{ ...}, ...>`?
  - [x] some field in a `Page` that have very generic names
  - [x] ~some type for HTML strings similar to `UserId`?~
  - [x] some common type for the error part of a `Result`
- [x] integration test for page-handler, apply-standard-layout, render-page to e.g. ensure that og tags are correctly filled

**Comment by hdrury1** [comment]
Asset for card:

![sciety-twitter-summary-card](https://user-images.githubusercontent.com/17023702/97985220-e6a5e680-1dcf-11eb-99aa-3f2af6c66990.jpg)

**Comment by thewilkybarkid** [comment]
We should strive for the best quality logos, so SVG should be our source (then use WebP as Twitter doesn't read SVGs).

**Comment by hdrury1** [comment]
SVG available in Slack

**Comment by giorgiosironi** [comment]
This is on `staging`:
![Screenshot_2020-11-03 Latest Tweets Twitter](https://user-images.githubusercontent.com/160299/98010858-1fa18380-1def-11eb-9b0e-212d4fef8267.png)
The image needed to be an absolute URL so not on `prod` yet as it missed the release.

**Comment by thewilkybarkid** [comment]
Facebook debugger: https://developers.facebook.com/tools/debug/
LinkedIn: https://www.linkedin.com/post-inspector/inspect/

**Comment by giorgiosironi** [comment]
https://cards-dev.twitter.com/validator
